name: Build NovaCraft Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build NovaCraft Linux
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3



    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc
        
    - name: Clone Classicube, Plugin and Compile Plugin
      run: |
        git clone https://github.com/UnknownShadow200/ClassiCube.git
        cd ClassiCube
		    wget https://raw.githubusercontent.com/mastergive514/NovaCraft2/main/main.c
		    cc main.c -o novacraft.so -shared -fPI
        mkdir -p output
        cp novacraft.so /output/
    
        

    
    - name: Upload Plugin
      uses: actions/upload-artifact@v3
      with:
        name: NovaCraft
        path: ClassiCube/output/
