name: Build for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build NovaCraft for Windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 g++-mingw-w64 mingw-w64-tools

      - name: Clone Classicube, Download Plugin, and Compile
        run: |
          git clone https://github.com/UnknownShadow200/ClassiCube.git
          cd ClassiCube
          wget https://raw.githubusercontent.com/mastergive514/NovaCraft2/main/main.c
          wget https://cdn.classicube.net/client/release/win32/ClassiCube.exe
          gendef ClassiCube.exe
          dlltool -d ClassiCube.def -l libClassiCube.a -D ClassiCube.exe
          mkdir output
          gcc main.c -o novacraft.dll -s -shared -L . -lClassiCube
          cp novacraft-x86.dll output/

      - name: Upload Plugin
        uses: actions/upload-artifact@v3
        with:
          name: NovaCraft
          path: ClassiCube/output/
